#!/bin/bash
#
# Builds Dockerfile.
#
set -o nounset -o errexit -o pipefail

declare -r script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

function die() { echo >&2 "$@"; exit 1; }

docker build --tag django-docker .
